### ISSUE TITLE
Doesn't support multiple address in the format specified in help

### ISSUE THREAD

**Issue by klui2k1** [medo64/MagiWOL#4]
I'm using this with mRemoteNG and discovered wol.exe program doesn't interpret multiple addresses correctly.

It will say Invalid MAC address address1 address2

wol.exe /wake:address1 /wake:address2 /wake:address3 will work but I would like to keep using the MAC Address variable and fill only MAC addresses there and execute wol.exe /wake:"%MACADDRESS%"

**Comment by medo64** [comment]
Reworked command line support in #13e5a1eadf5cbb5bef630eb65501ec4326702ed6.
It should now be possible to execute:

    wol.exe /wake:%MACADDRESS%
